com.ionic.keyboard 1.0.4 "Keyboard"
com.maginsoft.mfilechooser 1.0.0 "Maginsoft FileChooser"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.0.0 "Whitelist"
net.yoik.cordova.plugins.screenorientation 1.3.4 "Screen Orientation"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"
org.apache.cordova.globalization 0.3.4 "Globalization"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.jshybugger.cordova 4.5.9 "jsHybugger"
